#!/usr/bin/env python3
"""Generate art/glyphs/pocket-chronometer.glyph — the pocket chronometer item.

A copper-cased pocket watch echoing the Chronometer block's palette: a copper
case ring (highlight upper-left, occlusion lower-right), a night-slate dial, two
candleglow hands, moonlight hour ticks at 12/3/6/9, a redstone centre pin, and a
copper fob loop at the crown. 32px so the case and hands read at item scale;
1px ink outline; 1px transparent margin. Re-render the sprite with:

    python3 .ai/skills/mc-textures/scripts/glyph.py art/glyphs/pocket-chronometer.glyph \
        -o src/main/resources/assets/respite/textures/item/pocket_chronometer.png
"""
import math
import os

N = 32
CX, CY = 15.5, 18.0          # watch-body centre (low, to leave the fob room up top)
R_OUT = 12.6                 # outer ink radius
R_CASE = 11.4                # copper/ink boundary
R_IN = 8.9                   # dial/copper boundary (inner ink ring at R_IN..R_IN+0.8)
R_FACE = 8.2                 # dial face radius

# token -> (legend comment); '.' and 'K' handled specially
LEGEND = [
    (".", "transparent"),
    ("K", "ink"),
    ("1", "#eb8a5c                  # copper highlight"),
    ("2", "#c96a43                  # copper"),
    ("3", "#9c4e2f                  # copper shadow"),
    ("4", "#7a3a22                  # copper occlusion"),
    ("N", "#232838                  # dial slate"),
    ("n", "#1a1f2e                  # dial slate deep"),
    ("w", "#46527e                  # dial sheen speck"),
    ("S", "respite.candleglow-pale  # hand highlight / tip"),
    ("s", "respite.candleglow       # hand body"),
    ("m", "respite.moonlight        # hour ticks"),
    ("R", "#e04635                  # centre pin bright"),
    ("r", "#b3271e                  # centre pin"),
]

grid = [["." for _ in range(N)] for _ in range(N)]


def dist(c, r):
    return math.hypot(c - CX, r - CY)


def copper_tone(c, r, d):
    # Directional light from the upper-left, biased darker toward the outer edge.
    nx, ny = (c - CX), (r - CY)
    norm = max(dist(c, r), 0.001)
    lit = (-nx - ny) / (norm * math.sqrt(2))      # +1 upper-left, -1 lower-right
    edge = (d - R_IN) / (R_CASE - R_IN)            # 0 inner .. 1 outer
    v = lit - 0.9 * edge
    if v > 0.45:
        return "1"
    if v > -0.15:
        return "2"
    if v > -0.7:
        return "3"
    return "4"


# --- watch body: rings + dial face ---
for r in range(N):
    for c in range(N):
        d = dist(c, r)
        if d <= R_OUT + 0.5 and d > R_CASE:
            grid[r][c] = "K"
        elif d <= R_CASE and d > R_IN:
            grid[r][c] = copper_tone(c, r, d)
        elif d <= R_IN and d > R_FACE:
            grid[r][c] = "K"
        elif d <= R_FACE:
            grid[r][c] = "n" if d > R_FACE - 1.4 else "N"

# --- hour ticks at 12 / 3 / 6 / 9 (just inside the dial edge) ---
for ang in (-90, 0, 90, 180):
    a = math.radians(ang)
    for rad in (R_FACE - 1.0, R_FACE - 2.0):
        tc = int(round(CX + rad * math.cos(a)))
        tr = int(round(CY + rad * math.sin(a)))
        if 0 <= tr < N and 0 <= tc < N and grid[tr][tc] in ("N", "n"):
            grid[tr][tc] = "m"

# --- two hands from the centre: hour short (upper-left), minute long (upper-right) ---
def draw_hand(angle_deg, length, tip):
    a = math.radians(angle_deg)
    steps = int(length * 3)
    for i in range(steps + 1):
        rad = length * i / steps
        c = int(round(CX + rad * math.cos(a)))
        r = int(round(CY + rad * math.sin(a)))
        if 0 <= r < N and 0 <= c < N and grid[r][c] in ("N", "n", "m"):
            grid[r][c] = tip if (i >= steps - 1) else "s"

draw_hand(-120, 4.6, "S")   # hour hand, toward ~10 o'clock
draw_hand(-38, 6.6, "S")    # minute hand, toward ~2 o'clock

# --- centre pin (2px) ---
for (r, c, t) in ((0, 0, "R"), (0, 1, "R"), (1, 0, "r"), (1, 1, "r")):
    grid[int(CY) + r][int(CX) + c] = t

# --- fob loop at the crown (copper ring with a hole), above the case ---
fob = [
    "......KKKK......",
    ".....K2211K.....",
    ".....K3..2K.....",
    ".....K32.1K.....",
    "......K11K......",
]
# place the 15-wide fob centred on CX (col 8..22), rows 0..4
FOB_COL0 = 8
for r, line in enumerate(fob):
    for i, ch in enumerate(line):
        if ch != "." and grid[r][FOB_COL0 + i] == ".":
            grid[r][FOB_COL0 + i] = ch

# --- emit the .glyph ---
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "pocket-chronometer.glyph")
lines = []
lines.append("# respite — pocket chronometer item (design/SPEC.md §5)")
lines.append("# GENERATED by pocket-chronometer.gen.py — edit the generator, not this file.")
lines.append("# A copper-cased pocket watch in the Chronometer's palette: copper case,")
lines.append("# night-slate dial, candleglow hands, moonlight hour ticks, redstone pin, fob loop.")
lines.append("size: 32")
lines.append("")
lines.append("legend:")
for tok, desc in LEGEND:
    lines.append(f"  {tok} {desc}")
lines.append("")
lines.append("frame:")
for row in grid:
    lines.append("  " + "".join(row))
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", out)
